name: food_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_signin_button: ^2.0.0
  firebase_auth: ^4.3.0
  google_sign_in: ^6.0.2
  cloud_firestore: ^4.5.1
  provider: ^6.0.5
  fluttertoast: ^8.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - lib/images/
  uses-material-design: true

